# 1. Convert List to 1D Array

Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array.

Expected Output:

Original List: [12.23, 13.32, 100, 36.32]
One-dimensional NumPy array: [ 12.23 13.32 100. 36.32]

In [1]:
import numpy as np
my_list = [12.23, 13.32, 100, 36.32]
my_array = np.array(my_list)
print(my_list)
print(my_array)

[12.23, 13.32, 100, 36.32]
[ 12.23  13.32 100.    36.32]


# 2. Create 3x3 Matrix (2?10)

Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

Expected Output:

[[ 2 3 4]
[ 5 6 7]
[ 8 9 10]]

In [11]:
my_list = []
for i in range(2,11):
    my_list.append(i)
my_array = np.array(my_list).reshape(3,3)
print(my_array)






[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


# 3. Null Vector (10) & Update Sixth Value

Write a NumPy program to create a null vector of size 10 and update the sixth value to 11.

[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Update sixth value to 11
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [15]:
my_array = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
my_array[5] = 11
my_array

array([ 0,  0,  0,  0,  0, 11,  0,  0,  0,  0])

# 4. Array from 12 to 38

Write a NumPy program to create an array with values ranging from 12 to 38.

Expected Output:

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]

In [16]:
my_array = np.arange(12,39)
my_array

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38])

# 5. Convert Array to Float Type

Write a NumPy program to convert an array to a floating type.

Sample output:

Original array
[1, 2, 3, 4]

In [19]:
my_array = np.array([1, 2, 3, 4])
my_array = my_array.astype(float)
my_array


array([1., 2., 3., 4.])

# 6. Celsius to Fahrenheit Conversion

Write a NumPy program to convert Centigrade degrees into Fahrenheit degrees. Centigrade values are stored in a NumPy array.

Sample Array [0, 12, 45.21, 34, 99.91]
[-17.78, -11.11, 7.34, 1.11, 37.73, 0. ]

Expected Output:

Values in Fahrenheit degrees:
[ 0. 12. 45.21 34. 99.91 32. ]

Values in Centigrade degrees:
[-17.78 -11.11 7.34 1.11 37.73 0. ]

Values in Centigrade degrees:
[-17.78 -11.11 7.34 1.11 37.73 0. ]

Values in Fahrenheit degrees:
[-0. 12. 45.21 34. 99.91 32. ]

In [23]:
Sample_list = [0, 12, 45.21, 34, 99.91]
sample_array = np.array(Sample_list)
result_array = (sample_array - 32) * (5/9)
result_array = result_array.round(2)
result_array

Sample_list1 = [-17.78, -11.11, 7.34, 1.11, 37.73, 0.]
sample_array1 = np.array(Sample_list1)
result_array1 = (9 *sample_array1 + 160) / 5
result_array1 = result_array1.round(2)
result_array1


array([-0.  , 12.  , 45.21, 34.  , 99.91, 32.  ])

# 7. Append Values to Array (Do self-tudy)

Write a NumPy program to append values to the end of an array.

Expected Output:

Original array:
[10, 20, 30]

After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]

In [25]:
my_list = [10, 20, 30]
my_array =np.array(my_list)
new_array = np.append(my_array, [40, 50, 60, 70, 80, 90])
new_array


array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# 8. Array Statistical Functions (Do self-tudy)

Create a random NumPy array of 10 elements and calculate the mean, median, and standard deviation of the array.

In [ ]:
my_array = np.random.randn(10)
mean_array = np.mean(my_array)
mean_array



np.float64(-0.2667635711107368)

In [32]:
median_array = np.median(my_array)
median_array

np.float64(-0.3853787556653577)

In [33]:
std_array = np.std(my_array)
std_array

np.float64(0.9692321651670835)

# 9 Find min and max 

Create a 10x10 array with random values and find the minimum and maximum values.

In [34]:
my_array = np.random.randn(10,10)
max_array = np.max(my_array)
mean_array

np.float64(-0.2667635711107368)

In [36]:
my_array = np.random.randn(10,10)
min_array = np.min(my_array)
min_array

np.float64(-2.6577502998974647)

# 10 

Create a 3x3x3 array with random values.

In [39]:
my_array = np.random.randn(3,3,3)
my_array

array([[[ 1.21579342,  1.80466358,  1.99623024],
        [ 0.54497616, -0.48506308, -0.48243444],
        [ 0.51610151,  0.42724082, -0.81134448]],

       [[-0.14843508,  2.37583949, -0.6930156 ],
        [ 0.57204359, -1.16545801, -0.36331058],
        [-0.6386065 , -0.84437909, -1.62755479]],

       [[ 0.28231565, -1.56987076,  0.02107994],
        [-0.45451289, -0.17032383,  1.28136113],
        [-0.98314744,  1.42926684, -0.44153562]]])